### ISSUE TITLE
Working with speclj and exception

### ISSUE THREAD

**Issue by fdabrao** [maxbrunsfeld/wishful#1]
Hello,

I´m trying to use it with speclj like:
`(defn mu [] "Some text")`
`(spy-on (mu) (throw (Exception. "Other text")))`

and `(should-throw exception "Other text" (mu))`.
Am I doing it correctly?

Regards

**Comment by maxbrunsfeld** [comment]
I believe that currently, spy values are going to be evaluated eagerly, so the exception will be thrown when *defining* the `mu` spy, not when calling `mu`. 😬  Sorry about that. Maybe it would be better for the `spy-on` macro to evaluate the return values lazily?

**Comment by fdabrao** [comment]
I think so, I had to use `with-redefs` to do this evaluation in call time. Why don´t you see how it works? 
I liked this lib because it shows tests to be more clear. But, I had to change to `with-redefs`.

Best Regards

**Comment by maxbrunsfeld** [comment]
Yeah, `spy-on` uses `with-redefs` internally, but I guess I'm calling it in a way that evaluates the forms. If you're interested in submitting a PR to make your use case work correctly, I'd definitely merge it!

**Comment by fdabrao** [comment]
Sorry my dumb newbe pull request experience, I don´t know how to figure out to do this. I´ll read about it and pull it out. Regards
